### ISSUE TITLE
Frozen console

### ISSUE THREAD

**Issue by TuomLarsen** [willprice/python-omxplayer-wrapper#37]
Hello!

When I try to run python smoke-tests/test2.py, it plays the videos but when it exits I cannot type in console anymore. More precisely, I can type but nothing shows up but it's there somewhere because when I (blindly) hit up-arrow key and enter, it stars playing again. It's just the console wont display anything I type after I run python-omxplayer-wrapper.

I'm on RPi 2, Raspian Jessie 2015-09-24.

**Comment by willprice** [comment]
Hi @TuomLarsen, This is a known issue, I'm not quite sure what causes it though. Initially I thought it might be OMXPlayer reading key presses and when it quits it doesn't return focus back to the shell, but as you've pointed out, the shell is receiving characters, they just aren't appearing.

As a crap work around I tend to run REPLs in tmux so that I can kill the pane and create a new one quickly--sorry I don't have a better response.

**Comment by Aminpro** [comment]
Please refer to Pull Request #40 
That fixed the problem.

**Comment by willprice** [comment]
Fixed in #40

**Comment by willprice** [comment]
I can still observe this issue in the `develop` branch, redirecting stdin to `devnull` leaves the console usable. I think this is a more robust fix than killing with `SIGINT` as it allows the console to be used during interactive sessions.
